// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr4aRz6-b4Xw3q3esRlDdpVtiRLL3rMjU',
    appId: '1:1082727336838:web:a48f2c36dcd266336cfa07',
    messagingSenderId: '1082727336838',
    projectId: 'whatsapp-abdo-feac3',
    authDomain: 'whatsapp-abdo-feac3.firebaseapp.com',
    storageBucket: 'whatsapp-abdo-feac3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEK3ybGnWYIl6pQyyRnbGoRgSJQE-w8F8',
    appId: '1:1082727336838:android:18c03665c4f851076cfa07',
    messagingSenderId: '1082727336838',
    projectId: 'whatsapp-abdo-feac3',
    storageBucket: 'whatsapp-abdo-feac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBSfKiYXoETzijnhVg3iRW2sGTzCzaD0',
    appId: '1:1082727336838:ios:7787b8c078733bdf6cfa07',
    messagingSenderId: '1082727336838',
    projectId: 'whatsapp-abdo-feac3',
    storageBucket: 'whatsapp-abdo-feac3.appspot.com',
    iosBundleId: 'com.example.whatsappAbdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBSfKiYXoETzijnhVg3iRW2sGTzCzaD0',
    appId: '1:1082727336838:ios:7787b8c078733bdf6cfa07',
    messagingSenderId: '1082727336838',
    projectId: 'whatsapp-abdo-feac3',
    storageBucket: 'whatsapp-abdo-feac3.appspot.com',
    iosBundleId: 'com.example.whatsappAbdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr4aRz6-b4Xw3q3esRlDdpVtiRLL3rMjU',
    appId: '1:1082727336838:web:92266635aa7682c86cfa07',
    messagingSenderId: '1082727336838',
    projectId: 'whatsapp-abdo-feac3',
    authDomain: 'whatsapp-abdo-feac3.firebaseapp.com',
    storageBucket: 'whatsapp-abdo-feac3.appspot.com',
  );
}
